//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerater.Utility.EasyMacro.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGenerater.Utility.EasyMacro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   08	8e
        ///09	8f
        ///0d	9c
        ///14	ba
        ///1b	81
        ///20	b9
        ///2c	d4
        ///31	82
        ///32	83
        ///33	84
        ///34	85
        ///35	86
        ///36	87
        ///37	88
        ///38	89
        ///39	8a
        ///3a	8b
        ///41	9e
        ///42	b0
        ///43	ae
        ///44	a0
        ///45	92
        ///46	a1
        ///47	a2
        ///48	a3
        ///49	97
        ///4a	a4
        ///4b	a5
        ///4c	a6
        ///4d	b2
        ///4e	b1
        ///4f	98
        ///50	99
        ///51	90
        ///52	93
        ///53	9f
        ///54	94
        ///55	96
        ///56	af
        ///57	91
        ///58	ad
        ///59	95
        ///5a	ac
        ///60	d2
        ///61	cf
        ///62	d0
        ///63	d1
        ///64	cb
        ///65	cc
        ///66	cd
        ///67	c7
        ///68	c8
        ///69	c9
        ///6a	b7
        ///6b	ce
        ///6d	ca
        ///6e	d3
        ///6f	ab
        ///70	bb
        ///71	bc
        ///72	bd
        ///73	be
        ///74	bf
        ///75	c0
        ///76	c1
        ///77	c2
        ///78	c3
        ///79	c4
        ///7a	d7
        ///7b	d8
        ///90	c5
        ///91	c6
        ///a0	aa
        ///a[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HardwareCode {
            get {
                return ResourceManager.GetString("HardwareCode", resourceCulture);
            }
        }
    }
}
